import torch
import math
import warnings


def neighbor_indices(sz=16):
    index_mask = torch.zeros((sz * sz, sz * sz), dtype=torch.float16)
    divide_num = torch.zeros((sz * sz), dtype=torch.long)
    for _im in range(sz * sz):
        if _im == 0:
            index_set = torch.tensor([_im, _im + 1, _im + sz, _im + (sz + 1)])
        elif _im == (sz - 1):
            index_set = torch.tensor([_im - 1, _im, _im + (sz - 1), _im + sz])
        elif _im == (sz * sz - sz):
            index_set = torch.tensor([_im - sz, _im - (sz - 1), _im, _im + 1])
        elif _im == (sz * sz - 1):
            index_set = torch.tensor([_im - (sz + 1), _im - sz, _im - 1, _im])

        elif ((1 <= _im) and (_im <= (sz - 2))):
            index_set = torch.tensor([_im - 1, _im, _im + 1, _im + (sz - 1), _im + sz, _im + (sz + 1)])
        elif (((sz * sz - sz + 1) <= _im) and (_im <= (sz * sz - 2))):
            index_set = torch.tensor([_im - (sz + 1), _im - sz, _im - (sz - 1), _im - 1, _im, _im + 1])
        elif (_im % sz == 0):
            index_set = torch.tensor([_im - sz, _im - (sz - 1), _im, _im + 1, _im + sz, _im + (sz + 1)])
        elif ((_im + 1) % sz == 0):
            index_set = torch.tensor([_im - (sz + 1), _im - sz, _im - 1, _im, _im + (sz - 1), _im + sz])
        else:
            index_set = torch.tensor(
                [_im - (sz + 1), _im - sz, _im - (sz - 1), _im - 1, _im, _im + 1, _im + (sz - 1), _im + sz,
                 _im + (sz + 1)])
        index_mask[_im][index_set] = 1.
        divide_num[_im] = index_set.size(0)
    return index_mask, divide_num


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor