dataset_name: CUB
data_roots: "/mnt/windows/datasets/CUB_200_2011_and_CUBV2/CUB"
metadata_root: "metadata/CUB"

num_classes: 200
lr: 5.0e-5
lr_multiplier: 10
batch_size: 128
alpha: 100
output_channels: 3
drop_out_value_loc: 0.5
drop_out_value_cls: 0.5
epochs: 200
early_stopping_patience: 10

backbone: dinov2
embedding_dim: 384

cam_curve_interval: 0.005
resize_size: 256
crop_size: 224
resize_eval: 448
IMAGE_MEAN_VALUE: [0.485, 0.456, 0.406]
IMAGE_STD_VALUE: [0.229, 0.224, 0.225]

multi_contour_eval: false
iou_threshold_list: [30, 50, 70]


weight_decay: 0.01
log_dir: "./runs/cub"
experiment_name: "check_clean_repo"
workers: 8
